apiVersion: v1
kind: Service
metadata:
  name: axelar-metrics
spec:
  selector:
    app: axelar-node
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
