apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: axelar-node
spec:
  serviceName: axelar
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: axelar-node
  template:
    metadata:
      labels:
        app: axelar-node
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-config
          image: busybox
          command: ["sh", "-c"]
          args:
            - |
              mkdir -p /axelar/config && \
              cp -r /config/. /axelar/config/ && cp /config/* /axelar/
          volumeMounts:
            - name: configmap
              mountPath: /config
            - name: axelar-home
              mountPath: /axelar/config
      containers:
        - name: axelard
          image: axelarnet/axelar-core:v1.2.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting Axelar node..." && \
              mkdir -p /axelar/config && \
              cp -r /config/. /axelar/config/ && \
              axelard start --home /axelar --rpc.laddr tcp://0.0.0.0:26657
          ports:
            - containerPort: {{ .Values.service.rpcPort }}
              name: rpc
            - containerPort: {{ .Values.service.metricsPort }}
              name: metrics
          volumeMounts:
            - name: configmap
              mountPath: /config
            - name: axelar-home
              mountPath: /axelar
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: configmap
          configMap:
            name: axelar-config
        - name: axelar-home
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
